/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.baocao.gui;

import Proccess.HopDongController;
import com.mycompany.baocao.entity.HopDong;
import com.mycompany.baocao.entity.KhachThue;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author Tran Anh Tuan
 */
public class frmHopDong extends javax.swing.JFrame {

    /**
     * Creates new form frmHopDong
     */
    private DefaultTableModel tbKT = new DefaultTableModel();
    private DefaultTableModel tbHD = new DefaultTableModel();
    private HopDongController controller = new HopDongController();

    public frmHopDong() {
        initComponents();
        String[] rowKT = {"CMND", "Ten"};
        String[] rowHD = {"ID", "CMND", "Phong", "Gia phong", "Ngay vao o", "Trang thai"};
        tbHopDong.setModel(tbHD);
        tbKhachThue.setModel(tbKT);
        tbHD.setColumnIdentifiers(rowHD);
        tbKT.setColumnIdentifiers(rowKT);
        showKT();
        showHD();
    }

    public frmHopDong(String phong) {
        initComponents();
        String[] rowKT = {"CMND", "Ten"};
        String[] rowHD = {"ID", "CMND", "Phong", "Gia phong", "Ngay vao o", "Trang thai"};
        tbHopDong.setModel(tbHD);
        tbKhachThue.setModel(tbKT);
        tbHD.setColumnIdentifiers(rowHD);
        tbKT.setColumnIdentifiers(rowKT);
        showKT();
        showHD();
        txtPhong.setText(phong);
        showHDByPhong(txtPhong.getText());
        String status = controller.CheckStatus_Phong(phong);
        if (status.contains("đã cho thuê")) {
            btnTaoHopDong.setVisible(false);
            btnKTHopDong.setVisible(true);
            btnDonGia.setVisible(true);
            btnHoaDon.setVisible(true);
        } else {
            btnTaoHopDong.setVisible(true);
            btnKTHopDong.setVisible(false);
            btnDonGia.setVisible(false);
            btnHoaDon.setVisible(false);
        }
    }

    public final void showHDByPhong(String phong) {
        try {
            HopDong hd = controller.getHDByPhong(phong);
            txtCMND.setText(hd.getCmnd());
            txtIDHopDong.setText(hd.getId());
            txtTienPhong.setText(String.valueOf(hd.getGiaPhong()));
            txtNgayVaoO.setText(hd.getNgayVaoO());
        } catch (SQLException ex) {
            Logger.getLogger(frmHopDong.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    public final void showKT() {
        clearDataKT();
        List<KhachThue> lst = controller.getKhachThue();
        for (int i = 0; i < lst.size(); i++) {
            Object[] row = {
                lst.get(i).getCmnd(),
                lst.get(i).getTen()
            };
            tbKT.addRow(row);
        }
    }

    public final void clearDataKT() {
        int n = tbKT.getRowCount() - 1;
        for (int i = n; i >= 0; i--) {
            tbKT.removeRow(i);
        }
    }

    public final void clearTextKT() {
        txtTimCMND.setText("");
        txtTimTen.setText("");
    }

    public final void showHD() {
        clearDataHD();
        List<HopDong> lst = controller.getHopDong();
        for (int i = 0; i < lst.size(); i++) {
            Object[] row = {
                lst.get(i).getId(),
                lst.get(i).getCmnd(),
                lst.get(i).getPhong(),
                lst.get(i).getGiaPhong(),
                lst.get(i).getNgayVaoO(),
                lst.get(i).getTrangThai(),};
            tbHD.addRow(row);
        }
    }

    public final void clearDataHD() {
        int n = tbHD.getRowCount() - 1;
        for (int i = n; i >= 0; i--) {
            tbHD.removeRow(i);
        }
    }

    public final void clearTextHD() {
        txtCMND.setText("");
        txtIDHopDong.setText("");
        txtNgayVaoO.setText("");
        txtTienPhong.setText("");
        txtPhong.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbKhachThue = new javax.swing.JTable();
        txtTimCMND = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        btnTimKhach = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        txtTimTen = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbHopDong = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtIDHopDong = new javax.swing.JTextField();
        txtCMND = new javax.swing.JTextField();
        txtPhong = new javax.swing.JTextField();
        txtTienPhong = new javax.swing.JTextField();
        txtNgayVaoO = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        btnTaoHopDong = new javax.swing.JButton();
        btnKTHopDong = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        btnDonGia = new javax.swing.JButton();
        btnHoaDon = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setText("Quản lý hợp đồng");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Khách thuê"));

        tbKhachThue.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Title 1", "Title 2"
            }
        ));
        tbKhachThue.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbKhachThueMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbKhachThue);

        jLabel8.setText("cmnd");

        btnTimKhach.setText("tìm kiếm");
        btnTimKhach.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimKhachActionPerformed(evt);
            }
        });

        jLabel9.setText("tên");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(btnTimKhach, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtTimTen, javax.swing.GroupLayout.DEFAULT_SIZE, 191, Short.MAX_VALUE)
                            .addComponent(txtTimCMND))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTimCMND, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTimTen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnTimKhach)
                .addGap(22, 22, 22))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Hợp đồng"));

        tbHopDong.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5", "Title 6"
            }
        ));
        tbHopDong.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbHopDongMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tbHopDong);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 588, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 151, Short.MAX_VALUE)
                .addContainerGap())
        );

        jLabel2.setText("ID hợp đồng");

        jLabel3.setText("CMND");

        jLabel4.setText("Phòng");

        jLabel5.setText("Tiền phòng");

        jLabel7.setText("Ngày vào ở");

        jButton2.setText("quay lại");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        btnTaoHopDong.setText("tạo hợp đồng");
        btnTaoHopDong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTaoHopDongActionPerformed(evt);
            }
        });

        btnKTHopDong.setText("kết thúc hợp đồng");
        btnKTHopDong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKTHopDongActionPerformed(evt);
            }
        });

        btnClear.setText("đặt lại");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });

        btnDonGia.setText("Đơn giá dịch vụ");
        btnDonGia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDonGiaActionPerformed(evt);
            }
        });

        btnHoaDon.setText("Hóa đơn");
        btnHoaDon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHoaDonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(327, 327, 327)
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnClear)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(26, 26, 26)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtIDHopDong, javax.swing.GroupLayout.DEFAULT_SIZE, 147, Short.MAX_VALUE)
                                    .addComponent(txtCMND)
                                    .addComponent(txtPhong))
                                .addGap(57, 57, 57)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtTienPhong, javax.swing.GroupLayout.DEFAULT_SIZE, 136, Short.MAX_VALUE)
                                    .addComponent(txtNgayVaoO))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnHoaDon)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnDonGia)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnKTHopDong)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnTaoHopDong)
                                .addGap(16, 16, 16)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel2)
                                .addComponent(txtIDHopDong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel5)
                                .addComponent(txtTienPhong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtCMND, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7)
                            .addComponent(txtNgayVaoO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtPhong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(btnTaoHopDong)
                    .addComponent(btnKTHopDong)
                    .addComponent(btnClear)
                    .addComponent(btnDonGia)
                    .addComponent(btnHoaDon))
                .addGap(17, 17, 17))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        frmMain fMain = new frmMain();
        fMain.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void btnTimKhachActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimKhachActionPerformed
        // TODO add your handling code here:
        String cmnd = txtTimCMND.getText();
        String ten = txtTimTen.getText();

        clearDataKT();
        List<KhachThue> lst = controller.searchKhachThue(cmnd, ten);
        for (int i = 0; i < lst.size(); i++) {
            Object[] row = {
                lst.get(i).getCmnd(),
                lst.get(i).getTen()
            };
            tbKT.addRow(row);
        }
        clearTextKT();
    }//GEN-LAST:event_btnTimKhachActionPerformed

    private void tbKhachThueMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbKhachThueMouseClicked
        // TODO add your handling code here:
        TableModel tableModel = tbKhachThue.getModel();
        int row = tbKhachThue.getSelectedRow();
        txtCMND.setText(tableModel.getValueAt(row, 0).toString());
    }//GEN-LAST:event_tbKhachThueMouseClicked

    private void btnTaoHopDongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTaoHopDongActionPerformed
        // TODO add your handling code here:
        String id = txtIDHopDong.getText();
        String cmnd = txtCMND.getText();
        String phong = txtPhong.getText();
        String ngayVaoO = txtNgayVaoO.getText();
        int tienPhong = Integer.parseInt(txtTienPhong.getText());
        String trangThai = "có hiệu lực";
        HopDong hd = new HopDong(id, cmnd, phong, tienPhong, ngayVaoO, trangThai);

        String status = controller.CheckStatus_Phong(phong);

        if (status.contains("đã cho thuê")) {
            JOptionPane.showMessageDialog(rootPane, "Phòng đã có người thuê không thể tạo hợp đồng");
        } else {
            try {
                boolean tao = controller.insertHD(hd);
                if (tao) {
                    JOptionPane.showMessageDialog(rootPane, "Tạo hợp đồng thành công");
                    boolean thayDoi = controller.updatePhongChoThue(phong);
                    if (thayDoi) {
                        JOptionPane.showMessageDialog(rootPane, "Cập nhật lại phòng thành công");
                        showHD();
                        clearTextHD();
                    }
                } else {
                    JOptionPane.showMessageDialog(rootPane, "Tạo hợp đồng không thành công");
                    showHD();
                    clearTextHD();
                }
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(rootPane, "Ban chua nhap day du thong tin");
            }
        }

    }//GEN-LAST:event_btnTaoHopDongActionPerformed

    private void btnKTHopDongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKTHopDongActionPerformed
        // TODO add your handling code here:
        String id = txtIDHopDong.getText();
        String phong = txtPhong.getText();

        String status = controller.CheckStatus_Phong(phong);

        if (status.contains("còn trống")) {
            JOptionPane.showMessageDialog(rootPane, "Phòng chưa có người thuê không thể kết thúc hợp đồng");
        } else {
            try {
                boolean tao = controller.updateHD(id);
                if (tao) {
                    JOptionPane.showMessageDialog(rootPane, "Kết thúc hợp đồng thành công");
                    boolean thayDoi = controller.updatePhongConTrong(phong);
                    if (thayDoi) {
                        JOptionPane.showMessageDialog(rootPane, "Cập nhật lại phòng thành công");
                    }
                } else {
                    JOptionPane.showMessageDialog(rootPane, "Kết thúc hợp đồng không thành công");
                }
            } catch (SQLException ex) {
                Logger.getLogger(frmHopDong.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        showHD();
        clearTextHD();
    }//GEN-LAST:event_btnKTHopDongActionPerformed

    private void tbHopDongMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbHopDongMouseClicked
        // TODO add your handling code here:
        TableModel tableModel = tbHopDong.getModel();
        int row = tbHopDong.getSelectedRow();
        txtIDHopDong.setText(tableModel.getValueAt(row, 0).toString());
        txtCMND.setText(tableModel.getValueAt(row, 1).toString());
        txtPhong.setText(tableModel.getValueAt(row, 2).toString());
        txtTienPhong.setText(tableModel.getValueAt(row, 3).toString());
        txtNgayVaoO.setText(tableModel.getValueAt(row, 4).toString());
    }//GEN-LAST:event_tbHopDongMouseClicked

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        // TODO add your handling code here:
        clearTextHD();
    }//GEN-LAST:event_btnClearActionPerformed

    private void btnDonGiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDonGiaActionPerformed
        // TODO add your handling code here:
        frmDonGiaDV fDonGiaDV = new frmDonGiaDV(txtIDHopDong.getText());
        fDonGiaDV.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnDonGiaActionPerformed

    private void btnHoaDonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHoaDonActionPerformed
        // TODO add your handling code here:
        frmHoaDon fDon = new frmHoaDon(txtIDHopDong.getText());
        fDon.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnHoaDonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmHopDong.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmHopDong.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmHopDong.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmHopDong.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmHopDong().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnDonGia;
    private javax.swing.JButton btnHoaDon;
    private javax.swing.JButton btnKTHopDong;
    private javax.swing.JButton btnTaoHopDong;
    private javax.swing.JButton btnTimKhach;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tbHopDong;
    private javax.swing.JTable tbKhachThue;
    private javax.swing.JTextField txtCMND;
    private javax.swing.JTextField txtIDHopDong;
    private javax.swing.JTextField txtNgayVaoO;
    private javax.swing.JTextField txtPhong;
    private javax.swing.JTextField txtTienPhong;
    private javax.swing.JTextField txtTimCMND;
    private javax.swing.JTextField txtTimTen;
    // End of variables declaration//GEN-END:variables
}
